### ISSUE TITLE
TypeError: can not serialize 'Series' object while trying to read remote intake_sql.intake_sql.SQLSource

### ISSUE THREAD

**Issue by emericauger** [intake/intake#613]
Using intake-sql.
It seems because msgpack recieve invalid data types in the response.

Traceback (server side) :

```
Traceback (most recent call last):
  File "/opt/conda/envs/intake/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/conda/envs/intake/lib/python3.9/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/opt/conda/envs/intake/lib/python3.9/site-packages/intake/cli/server/server.py", line 329, in post
    self.write(msgpack.packb(response, **pack_kwargs))
  File "/opt/conda/envs/intake/lib/python3.9/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'Series' object
```

**Comment by martindurant** [comment]
I think, essentially, you will need to have arrow installed for both the server and client environments ( https://github.com/intake/intake/pull/462 ). The branch that is getting activated should be giving you a meaningful error instead of the traceback you got.

**Comment by martindurant** [comment]
@danielballan , I know `tiled` takes a more directly principled view on how to serialise data over HTTP. Do you handle dataframes yet, can you imagine making an example where the server is channeling the catalogue and data from a SQL connection?

**Comment by martindurant** [comment]
@emericauger , I will investigate further next week, and may move this issue to intake-sql.

**Comment by emericauger** [comment]
> I think, essentially, you will need to have arrow installed for both the server and client environments ( #462 ). The branch that is getting activated should be giving you a meaningful error instead of the traceback you got.

Even with arrow installed the traceback is the same.
