### ISSUE TITLE
keyError: 'array' while trying to read  Array from remote cat with custom driver

### ISSUE THREAD

**Issue by emericauger** [intake/intake#616]
Hi,

It might be linked to [that issue comment](https://github.com/intake/intake/issues/612#issuecomment-901119892).
I made a very simple driver to read individual GeoTIFF files on a remote server via ssh. It works perfectly when the catalog is opened locally. When opened as a remote catalog, an exception is generated when the entry is read.

The driver is enabled both on server and client side, and has been tested on both machines. Maybe the approach is naive and some other things have to be implemented on the driver. 

<details>
<summary>
The driver : 
</summary>

```

import intake
import rasterio
import numpy as np
import fsspec as fs



class GeoTIFFSource(intake.source.base.DataSource):
    container = 'array'
    name = 'geotiff'
    version = '0.0.1'
    partition_access = True

    def __init__(self, file, metadata=None):
        self.remote_fs = fs.filesystem('ssh', host = 'xxx', username = 'xxx', password = 'xxx')
        self.file = self.remote_fs.open(file)
        super(GeoTIFFSource, self).__init__(
            metadata=metadata
        )

    def _get_schema(self):
        return intake.source.base.Schema(
             dtype = float,
             shape = (1420, 1750),
             npartitions = 1
        )

    def _get_partition(self, i):
        with rasterio.open(self.file) as raster:
            self.array = raster.read(1)
        return self.array

    def read(self):
        self._load_metadata()
        return ([self.read_partition(i) for i in range(self.npartitions)])

    def _close(self):
        self.file.close()
        pass
``` 
</details>

<details >
<summary>
The traceback : 
</summary>

Traceback (most recent call last):
  File "/opt/conda/envs/intake/lib/python3.9/site-packages/intake/catalog/base.py", line 350, in __getattr__
    return self[item]  # triggers reload_on_change
  File "/opt/conda/envs/intake/lib/python3.9/site-packages/intake/catalog/base.py", line 400, in __getitem__
    return e()
  File "/opt/conda/envs/intake/lib/python3.9/site-packages/intake/catalog/entry.py", line 77, in __call__
    s = self.get(**kwargs)
  File "/opt/conda/envs/intake/lib/python3.9/site-packages/intake/catalog/remote.py", line 450, in get
    return open_remote(
  File "/opt/conda/envs/intake/lib/python3.9/site-packages/intake/catalog/remote.py", line 504, in open_remote
    source = container_map[container](url, http_args, **response)
  File "/opt/conda/envs/intake/lib/python3.9/site-packages/intake/utils.py", line 206, in __getitem__
    return self._registry[key]
KeyError: 'array'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/intake/lib/python3.9/site-packages/intake/catalog/base.py", line 352, in __getattr__
    raise AttributeError(item) from e
AttributeError: _name of the entry in the catalog_

</details>

Thanks !

**Comment by martindurant** [comment]
Could you please show the contents of your `container_map` and `_registry` dicts? You can either find them within the intake codebase, or just run pdb.pm() in the client having received the exception.

**Comment by emericauger** [comment]
```
container_map = ContainerRegistryView({'dataframe': <class 'intake.container.dataframe.RemoteDataFrame'>, 'python': <class 'intake.container.semistructured.RemoteSequenceSource'>, 'ndarray': <class 'intake.container.ndarray.RemoteArray'>, 'numpy': <class 'intake.container.ndarray.RemoteArray'>, 'catalog': <class 'intake.catalog.base.RemoteCatalog'>, 'xarray': <class 'intake_xarray.xarray_container.RemoteXarray'>})
 ```


```
_registry = {'dataframe': <class 'intake.container.dataframe.RemoteDataFrame'>, 'python': <class 'intake.container.semistructured.RemoteSequenceSource'>, 'ndarray': <class 'intake.container.ndarray.RemoteArray'>, 'numpy': <class 'intake.container.ndarray.RemoteArray'>, 'catalog': <class 'intake.catalog.base.RemoteCatalog'>, 'xarray': <class 'intake_xarray.xarray_container.RemoteXarray'>}
```

**Comment by martindurant** [comment]
OK!
So
```
class GeoTIFFSource(intake.source.base.DataSource):
    container = 'array'
```

should be
```
class GeoTIFFSource(intake.source.base.DataSource):
    container = 'ndarray'
```

I wonder, should you be using intake-xarray for this?

**Comment by emericauger** [comment]
Yes, I am aware that intake-xarray can do this but i wanted to understand how things work when using remote catalogs, especially regarding the issue  (https://github.com/intake/intake/issues/612)

Almost there thanks to the `container = 'ndarray' `fix ! I probably have a problem with how I deal with the single partition : 

```
File "/opt/anaconda3/lib/python3.7/site-packages/intake/catalog/base.py", line 339, in __getattr__
    return self[item]  # triggers reload_on_change
  File "/opt/anaconda3/lib/python3.7/site-packages/intake/catalog/base.py", line 387, in __getitem__
    return e()
  File "/opt/anaconda3/lib/python3.7/site-packages/intake/catalog/entry.py", line 77, in __call__
    s = self.get(**kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/intake/catalog/remote.py", line 83, in get
    getshell=self.getshell)
  File "/opt/anaconda3/lib/python3.7/site-packages/intake/catalog/remote.py", line 130, in open_remote
    source = container_map[container](url, http_args, **response)
  File "/opt/anaconda3/lib/python3.7/site-packages/intake/container/ndarray.py", line 25, in __init__
    for c in tuple(kwargs.get('chunks', (-1, ))))
  File "/opt/anaconda3/lib/python3.7/site-packages/intake/container/ndarray.py", line 25, in <genexpr>
    for c in tuple(kwargs.get('chunks', (-1, ))))
TypeError: 'int' object is not iterable
```

**Comment by martindurant** [comment]
Can you find out what "chunks" is for you?

**Comment by emericauger** [comment]
Ok, I passed an empty dict to "chunks" to intake.source.base.Schema inside the _get_schema method of my driver 
(I only need one partition / one chunk of data to be returned).
I now have an exception on the server side : 

```
Traceback (most recent call last):
  File "/opt/conda/envs/intake/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/conda/envs/intake/lib/python3.9/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/opt/conda/envs/intake/lib/python3.9/site-packages/intake/cli/server/server.py", line 358, in post
    chunk = source.read_partition(partition)
  File "/opt/conda/envs/intake/lib/python3.9/site-packages/intake/source/base.py", line 326, in read_partition
    if i < 0 or i >= self.npartitions:
TypeError: '<' not supported between instances of 'list' and 'int'
```

In that case, self.npartitions is equal to 1 and "i" is an empty list.
