### ISSUE TITLE
getting entry fails after update to 0.6.6

### ISSUE THREAD

**Issue by paolap** [intake/intake#686]
Hi, 
we have a couple of catalogues which work with intake 0.6.5 and fail to load entries with intake 0.6.6.
I'm not sure if there is something we need to change in the way we define the catalogues.

To test the issue I simplified one of the catalogues

**catalogue.yaml**

```
metadata:
    version: 1
sources:
    era5:
        description: |
            ECMWF ERA5 Reanalysis
            Requires access to /g/data/rt52
            Files managed by NCI, contact help@nci.org.au
            https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation
            https://opus.nci.org.au/display/ERA5/ERA5+Community+Home
        driver: intake_esm.esm_datastore
        args:
            esmcol_obj: '{{CATALOG_DIR}}/era5/catalogue.json'
```
**era5/catalogue.json**

```
{
  "id": "era5",
  "title": "ERA5 - ECMWF atmospheric reanalysis",
  "description": "ECMWF ERA5 Reanalysis",
  "assets": {
    "column_name": "path",
    "format": "netcdf"
  },
  "aggregation_control": {
    "variable_column_name": "file_variable",
    "groupby_attrs": [
      "dataset",
      "product_type",
      "file_variable"
    ],
    "aggregations": [
      {
        "type": "join_existing",
        "attribute_name": "date_range",
        "options": {
          "dim": "time"
        }
      }
    ]
  },
  "esmcat_version": "0.1.0",
  "catalog_file": "catalogue.csv.xz",
  "attributes": [
    {
      "column_name": "dataset"
    },
    {
      "column_name": "product_type"
    },
    {
      "column_name": "parameter"
    },
    {
      "column_name": "year"
    },
    {
      "column_name": "mode"
    },
    {
      "column_name": "level"
    },
    {
      "column_name": "date_range"
    },
    {
      "column_name": "file_variable"
    },
    {
      "column_name": "month"
    }
  ]
}
```

The packages in the conda environment are:
```
intake                    0.6.6             
intake-esm                2022.9.18        
intake-thredds            2022.8.19        
intake-xarray             0.6.0   
xarray                    2022.6.0          
appdirs                   1.4.4             
dask                      2022.9.1       
entrypoints               0.4          
pyyaml                    6.0            
fsspec                    2022.8.2          
jinja2                    3.1.2        
msgpack-python            1.0.4  
```

**This is the error:**
```
>>> import intake
>>> cat = intake.open_catalog('/g/data/ua8/Working/packages/intake-test/catalogue.yaml')
>>> era5 = cat.era5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/intake/catalog/base.py", line 391, in __getattr__
    return self[item]  # triggers reload_on_change
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/intake/catalog/base.py", line 436, in __getitem__
    s = self._get_entry(key)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/intake/catalog/utils.py", line 45, in wrapper
    return f(self, *args, **kwargs)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/intake/catalog/base.py", line 323, in _get_entry
    return entry()
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/intake/catalog/entry.py", line 77, in __call__
    s = self.get(**kwargs)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/intake/catalog/local.py", line 290, in get
    data_source = plugin(**open_args)
TypeError: __init__() got an unexpected keyword argument 'metadata'
```
where open_args is:

```
{'metadata': {'catalog_dir': '/g/data/ua8/Working/packages/intake-test/'}, 'esmcol_obj': '/g/data/ua8/Working/packages/intake-test//era5/catalogue.json'}
```
This is what cat._entries shows:

```
>>> cat._entries
{'era5': name: era5
container: xarray
plugin: ['esm_datastore']
driver: ['esm_datastore']
description: ECMWF ERA5 Reanalysis

Requires access to /g/data/rt52
Files managed by NCI, contact help@nci.org.au
https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation
https://opus.nci.org.au/display/ERA5/ERA5+Community+Home

direct_access: forbid
user_parameters: []
metadata: 
args: 
  esmcol_obj: {{CATALOG_DIR}}/era5/catalogue.json}
```
Using open_esm_datastore() to access the catalogue.json file works:

```
>>> data_catalog = intake.open_esm_datastore("/g/data/ua8/Working/packages/intake-test/era5/catalogue.json")
>>> data_catalog
<era5 catalog with 794 dataset(s) from 580644 asset(s)>
```
Finally these are the packages of the conda env that works:
```
intake                    0.6.5             
intake-esm                2021.8.17     
intake-thredds            2021.6.16        
intake-xarray             0.6.0 
xarray                    2022.3.0 
dask                      2022.6.1
appdirs                   1.4.4    
entrypoints               0.4                
pyyaml                    6.0              
fsspec                    2022.5.0        
jinja2                    3.0.3           
msgpack-python            1.0.3
```

Many thanks!

**Comment by martindurant** [comment]
I don't have an immediate thought for why this would be. Can you also please cross-post at intake-esm to see if anyone else is experiencing this?

**Comment by martindurant** [comment]
I find the same failure with 0.6.5 and 0.6.4.
cc @andersy005 , any ideas?

**Comment by paolap** [comment]
I was on leave for a few days now that I'm back I tried creating separate environmenst with just the packages I listed above, as the environments we used have many more packages installed.

I could confirmed the same results as my previous comment, and then I tried to install intake 0.6.6 with intake-esm  2021.8.17  and this combination also works. 

I finally created a third env with intake 0.6.5 and the latest intake-esm and with this is also failing.
So yes it looks like the issue is related to the new intake-esm, I'm cross-posting this in their repo now, thanks for looking into it

**Comment by andersy005** [comment]
> I find the same failure with 0.6.5 and 0.6.4. cc @andersy005 , any ideas?

this was caused by a bug in `intake-esm`. This has been addressed upstream.

**Comment by martindurant** [comment]
Perfect, thanks @andersy005
