### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by raybellwaves** [intake/intake#706]
I was testing https://github.com/DTN-Public/intake-pattern-catalog/pull/6 by building it and installing it.

I got ModuleNotFoundError: No module named 'requests'

```
>>> cat.folder_with_csvs.get_entry(num=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ray/miniforge3/envs/test_env/lib/python3.10/site-packages/intake/catalog/base.py", line 391, in __getattr__
    return self[item]  # triggers reload_on_change
  File "/Users/ray/miniforge3/envs/test_env/lib/python3.10/site-packages/intake/catalog/base.py", line 436, in __getitem__
    s = self._get_entry(key)
  File "/Users/ray/miniforge3/envs/test_env/lib/python3.10/site-packages/intake/catalog/utils.py", line 45, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/ray/miniforge3/envs/test_env/lib/python3.10/site-packages/intake/catalog/base.py", line 323, in _get_entry
    return entry()
  File "/Users/ray/miniforge3/envs/test_env/lib/python3.10/site-packages/intake/catalog/entry.py", line 78, in __call__
    if persist != 'never' and isinstance(s, PersistMixin) and s.has_been_persisted:
  File "/Users/ray/miniforge3/envs/test_env/lib/python3.10/site-packages/intake/source/base.py", line 196, in has_been_persisted
    from ..container.persist import store
  File "/Users/ray/miniforge3/envs/test_env/lib/python3.10/site-packages/intake/container/__init__.py", line 8, in <module>
    from .dataframe import RemoteDataFrame
  File "/Users/ray/miniforge3/envs/test_env/lib/python3.10/site-packages/intake/container/dataframe.py", line 11, in <module>
    from .base import RemoteSource, get_partition
  File "/Users/ray/miniforge3/envs/test_env/lib/python3.10/site-packages/intake/container/base.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

pip freeze:
intake==0.6.7

**Comment by raybellwaves** [comment]
Actually this perhaps is intentional to slim down deps. I can add requests to intake-pattern-catalog and therefore avoid bloating upstream deps

**Comment by martindurant** [comment]
It was intentional that you should have data format drivers available, which you cannot import/use without further requirements. In this case the driver in question is Intake's own server client, so I think we can regard it as basic enough it should be in the requirements.
