### ISSUE TITLE
Original Message: File(s) not found

### ISSUE THREAD

**Issue by forestbat** [intake/intake#794]
This is file structure of our minio server:
![图片](https://github.com/intake/intake/assets/23413915/f4dc8f8f-3557-46d6-b303-400735ff570d)

```
h5_dt = intk.datatypes.HDF5('s3://watermodel-pub/smap/2019/01/14/SMAP_L4_SM_gph_20190114T073000_Vv7032_001.h5', storage_options=conf.MINIO_PARAM)
h5_reader = intk.readers.DaskHDF(h5_dt)
h5_reader.read()

Traceback (most recent call last):
  File "C:\Users\Administrator\IdeaProjects\hydrodata\venv\Lib\site-packages\dask\backends.py", line 141, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\IdeaProjects\hydrodata\venv\Lib\site-packages\dask\dataframe\io\hdf.py", line 430, in read_hdf
    raise OSError(f"File(s) not found: {pattern}")
OSError: File(s) not found: s3://watermodel-pub/smap/2019/01/14/SMAP_L4_SM_gph_20190114T073000_Vv7032_001.h5
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\JetBrains\IntelliJIdea2023.3\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 3, in <module>
  File "C:\Users\Administrator\IdeaProjects\hydrodata\venv\Lib\site-packages\intake\readers\readers.py", line 96, in read
    return self._read(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\IdeaProjects\hydrodata\venv\Lib\site-packages\intake\readers\readers.py", line 224, in _read
    return self._func(data.url, key=data.path, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\IdeaProjects\hydrodata\venv\Lib\site-packages\dask\backends.py", line 143, in wrapper
    raise type(e)(
OSError: An error occurred while calling the read_hdf method registered to the pandas backend.
Original Message: File(s) not found: watermodel-pub/smap/2019/01/14/SMAP_L4_SM_gph_20190114T073000_Vv7032_001.h5
```
And other readers such as XarrayDatasetReader still don't work correctly. So what happened and how to solve it?

**Comment by martindurant** [comment]
`'s3://watermodel-pub/smap/2019/01/14/SMAP_L4_SM_gph_20190114T073000_Vv7032_001.h5'` looks like a folder. Isn't the actual path to one of the files 

`'s3://watermodel-pub/smap/2019/01/14/SMAP_L4_SM_gph_20190114T073000_Vv7032_001.h5/SMAP_L4_SM_gph_20190114T073000_Vv7032_001.h5' ?

**Comment by forestbat** [comment]
> `'s3://watermodel-pub/smap/2019/01/14/SMAP_L4_SM_gph_20190114T073000_Vv7032_001.h5'` looks like a folder. Isn't the actual path to one of the files
> 
> `'s3://watermodel-pub/smap/2019/01/14/SMAP_L4_SM_gph_20190114T073000_Vv7032_001.h5/SMAP_L4_SM_gph_20190114T073000_Vv7032_001.h5' ?

I'm sure this is a file not a directory which has file with the same name.

**Comment by martindurant** [comment]
What do you get if you query the path directly:
```
path = 's3://watermodel-pub/smap/2019/01/14/SMAP_L4_SM_gph_20190114T073000_Vv7032_001.h5'
fs = fsspec.filesystem("s3", **conf.MINIO_PARAM)
fs.info(path)
fs.cat_file(path, end=10)
```

**Comment by martindurant** [comment]
... or perhaps I should say, do you have a working line of code to load this same data with dask without intake?
